// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKx7iBnfW0d-BQgXanMH1sYlC_bSvRLY',
    appId: '1:958324745015:web:b7256b96b3237d633cf0b2',
    messagingSenderId: '958324745015',
    projectId: 'habit-ai-184ad',
    authDomain: 'habit-ai-184ad.firebaseapp.com',
    storageBucket: 'habit-ai-184ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcqwCifNYCQSlr-G5Gl0mzlcgkIS-6aw',
    appId: '1:958324745015:android:eb4f2f4031bff33d3cf0b2',
    messagingSenderId: '958324745015',
    projectId: 'habit-ai-184ad',
    storageBucket: 'habit-ai-184ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvlhxA-63RgvsbqD80iPqx9Qngl2LCU-8',
    appId: '1:958324745015:ios:a63b375576da69263cf0b2',
    messagingSenderId: '958324745015',
    projectId: 'habit-ai-184ad',
    storageBucket: 'habit-ai-184ad.firebasestorage.app',
    iosBundleId: 'com.andreistaicu.habitai',
    iosClientId: '958324745015-hbfhifjrvsbv91qaonqvpjr95thkgdka.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvlhxA-63RgvsbqD80iPqx9Qngl2LCU-8',
    appId: '1:958324745015:ios:a63b375576da69263cf0b2',
    messagingSenderId: '958324745015',
    projectId: 'habit-ai-184ad',
    storageBucket: 'habit-ai-184ad.firebasestorage.app',
    iosBundleId: 'com.andreistaicu.habitai',
    iosClientId: '958324745015-hbfhifjrvsbv91qaonqvpjr95thkgdka.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSKx7iBnfW0d-BQgXanMH1sYlC_bSvRLY',
    appId: '1:958324745015:web:9ce9f2bc168779b93cf0b2',
    messagingSenderId: '958324745015',
    projectId: 'habit-ai-184ad',
    authDomain: 'habit-ai-184ad.firebaseapp.com',
    storageBucket: 'habit-ai-184ad.firebasestorage.app',
  );
}
